const ProjectList = [{
    image:"https://sideeq12.github.io/imageBlog/card.png",
    message : "Frontend mentors challenge on Responsive grid card Layout",
    header : "simple Grid Component",
    github : "Repository",
    RepoUrl : "https://github.com/sideeq12/card--layout",
    Publish_url : "https://sideeq12.github.io/card--layout/",
    publish : "Preview",
},
{
    image:"https://sideeq12.github.io/imageBlog/purchase.png",
    message : "Responsive Purchased card design displaying business package plans. ",
    header : "Pricing component",
    github : "Repository",
    RepoUrl : "https://github.com/sideeq12/purchase-card",
    Publish_url : "https://sideeq12.github.io/purchase-card",
    publish : "Preview",
},
{
    image:"https://sideeq12.github.io/imageBlog/fylo.png",
    message : "Fylo landing page redesigned showcasing the business flow and logics with three sections of the pages, with mobile-first approach.",
    header : "Fylo Dark Theme landing page",
    github : "Repository",
    RepoUrl : "https://github.com/sideeq12/fylo-landing",
    Publish_url : "https://sideeq12.github.io/fylo-landing/",
    publish : "Preview",
},
{
    image:"https://cdn.dribbble.com/users/1314945/screenshots/11510711/media/42769e25859a8c8037977443cc8c7867.jpg?compress=1&resize=1200x900",
    message : "Webapp showing list of different monster illustration, you can search for your favourite monsters on the List. : Reactjs, APIs. ",
    header : "Monster",
    github : "Repository",
    RepoUrl : "https://github.com/sideeq12/MonsterRolodex",
    Publish_url : "https://sideeq12.github.io/MonsterRolodex/",
    publish : "Preview",
},
{
    image:"https://www.welovesolo.com/wp-content/uploads/vector/22/Hand-drawn-colored-musical-instruments-vector-06.jpg",
    message : "Podcast web application for streaming live data of different catalogues, you can search and listen to any podcast of yours: Reactjs, APIs, Nodejs, Expressjs. ",
    header : "PodSearch",
    github : "Repository",
    RepoUrl : "https://github.com/sideeq12/Podsearch",
    Publish_url : "https://pod-search-ki9syh.turbo360-vertex.com/",
    publish : "Preview",
},
{
    image:"https://assets.entrepreneur.com/content/3x2/2000/20150929184415-law-and-justice-patent.jpeg?auto=webp&quality=95&crop=16:9&width=675",
    message : "RESTful API showing Fundamental Laws in Nigeria, inorder to help LAW students to memorise faster and induviduals to know more about constitutional rights",
    header : "9jaLaw",
    github : "Repository",
    RepoUrl : "https://github.com/sideeq12/9jaLaw",
    Publish_url : "https://github.com/sideeq12/9jaLaw",
    publish : "Preview",
}]

export default ProjectList;